import Icons from '../Icons.jsx';
import DateInput from '../DateInput.jsx';

const SalesForm = ({
    date, setDate, isDateLocked, setDateLockModalOpen, setIsDateLocked,
    category, setCategory,
    clientName, setClientName, clientCpf, setClientCpf, clientPhone, setClientPhone,
    clientEmail, setClientEmail, clientDob, setClientDob, clientAddress, setClientAddress,
    clientNumber, setClientNumber, clientCity, setClientCity, clientZip, setClientZip,
    clientState, setClientState, clientNeighborhood, setClientNeighborhood,
    items, newItemQty, setNewItemQty, newItemType, setNewItemType, newItemDesc, setNewItemDesc,
    newItemRam, setNewItemRam, newItemColor, setNewItemColor, newItemImei, setNewItemImei,
    newItemFinanced, setNewItemFinanced, newItemPrice, setNewItemPrice,
    newItemDiscount, setNewItemDiscount, newItemDiscountPercent, setNewItemDiscountPercent,
    editingItemId, setEditingItemId,
    exchangeAction, setExchangeAction,
    paymentList, currentPaymentMethod, setCurrentPaymentMethod,
    currentPaymentType, setCurrentPaymentType, currentPaymentAmount, setCurrentPaymentAmount,
    currentInstallments, setCurrentInstallments, editingPaymentId, setEditingPaymentId,
    clientSource, setClientSource,
    paymentObservation, setPaymentObservation,
    editingId, resetForm,
    totalAmount, totalDiscount, finalTotal, remainingToPay, totalPaid, changeAmount,
    handleAddItem, handleEditItem, handleAddPayment, handleEditPayment, handleRemovePayment,
    handleSubmit, handleCpfChange, handleZipChange, maskPhone, maskDateStrict, maskIMEI,
    handleItemPriceChange, handlePercentChange, handleDiscountValChange,
    handleCurrentPaymentAmountChange, getPaymentStyles,
    setClientSearchModalOpen, handleSaveClient,
    CATEGORIES_LIST, PRODUCT_TYPES, RAM_STORAGE_OPTIONS, PAYMENT_METHODS, PAYMENT_TYPES, UF_LIST,
    formatCurrency
}) => {
    return (
        <>
            <div className="classic-frame rounded-[3rem] shadow-vision border border-white/10 overflow-hidden no-print fade-in-up backdrop-blur-md">
                <div className={`h-1 w-full bg-gradient-to-r ${editingId ? 'from-odoo-400 via-odoo-500 to-odoo-400 animate-pulse' : 'from-odoo-600 via-odoo-400 to-odoo-600'}`}></div>
                <div className="p-12 space-y-12">
                    <form onSubmit={handleSubmit} className="space-y-12">
                        <div className="grid grid-cols-1 md:grid-cols-12 gap-8">
                            <div className="md:col-span-6 space-y-3"><label className="text-[11px] font-bold text-slate-500 uppercase tracking-widest ml-3">Data do Lançamento</label><div className="relative group"><DateInput required value={date} onChange={e => { setDate(e.target.value); setIsDateLocked(true); }} className={`w-full p-5 rounded-[1.5rem] outline-none text-lg font-bold placeholder-slate-600 ${isDateLocked ? 'opacity-60 cursor-not-allowed' : ''}`} />{isDateLocked && <div className="absolute inset-0 z-10 cursor-lock rounded-[1.5rem] flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-black/40 backdrop-blur-[2px]" onClick={() => setDateLockModalOpen(true)}><Icons.Lock className="w-8 h-8 text-slate-400" /></div>}</div></div>
                            <div className="md:col-span-6 space-y-3"><label className="text-[11px] font-bold text-slate-500 uppercase tracking-widest ml-3">Categoria</label><div className="relative"><select required value={category} onChange={e => setCategory(e.target.value)} className="w-full p-5 rounded-[1.5rem] outline-none text-lg font-bold appearance-none cursor-pointer pr-10"><option value="" className="text-black bg-white">Selecione...</option>{CATEGORIES_LIST.map(c => <option key={c} value={c} className="text-black bg-white">{c}</option>)}</select><div className="absolute right-6 top-1/2 -translate-y-1/2 pointer-events-none text-slate-500"><Icons.ChevronLeft className="-rotate-90 w-5 h-5" /></div></div></div>

                            <div className="md:col-span-12 border border-amber-500/20 bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-md rounded-[2.5rem] p-10 shadow-lg shadow-amber-500/10 transition-all duration-300 hover:shadow-amber-500/20 hover:border-amber-500/30">
                                <div className="flex justify-between items-center mb-8"><h3 className="text-xl font-bold text-slate-200 flex items-center gap-4 font-display"><div className="p-3 bg-gradient-to-br from-amber-500/20 to-yellow-500/10 rounded-2xl shadow-lg shadow-amber-500/20 text-amber-400 border border-amber-500/30"><Icons.User className="w-6 h-6" /></div> Dados do Cliente</h3><div className="flex gap-4"><button type="button" onClick={() => { setClientSearchModalOpen(true); }} className="px-6 py-4 bg-amber-500/10 text-amber-400 rounded-2xl text-xs font-bold hover:shadow-lg hover:shadow-amber-500/30 transition-all active:scale-95 border border-amber-500/20 hover:bg-amber-500/20">Importar</button><button type="button" onClick={() => { setClientName(''); setClientCpf(''); setClientPhone(''); setClientEmail(''); setClientDob(''); setClientAddress(''); setClientNumber(''); setClientCity(''); setClientZip(''); setClientState(''); setClientNeighborhood(''); }} className="px-6 py-4 bg-red-500/10 text-red-400 rounded-2xl text-xs font-bold hover:shadow-lg hover:shadow-red-500/30 transition-all active:scale-95 border border-red-500/20 hover:bg-red-500/20 flex items-center gap-1.5"><Icons.X className="w-3.5 h-3.5" /> Limpar</button><button type="button" onClick={handleSaveClient} className="px-6 py-4 bg-emerald-500/10 text-emerald-400 rounded-2xl text-xs font-bold flex items-center gap-2 shadow-lg shadow-emerald-500/30 hover:shadow-emerald-500/50 transition-all active:scale-95 border border-emerald-500/20 hover:bg-emerald-500/20"><Icons.Save className="w-4 h-4" /> Salvar Cadastro</button></div></div>
                                <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
                                    <div className="md:col-span-8 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">Nome Completo</label><input type="text" required placeholder="Nome do Cliente" value={clientName} onChange={e => setClientName(e.target.value)} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-4 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">CPF</label><input type="text" placeholder="000.000.000-00" inputMode="numeric" value={clientCpf} onChange={handleCpfChange} className="w-full p-5 rounded-[1.5rem] text-sm font-mono outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-2 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">CEP</label><input type="text" placeholder="00000-000" inputMode="numeric" value={clientZip} onChange={handleZipChange} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-5 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">Endereço</label><input type="text" placeholder="Rua, Av..." value={clientAddress} onChange={e => setClientAddress(e.target.value)} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-2 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">Nº</label><input type="text" placeholder="123" value={clientNumber} onChange={e => setClientNumber(e.target.value)} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-3 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">Bairro</label><input type="text" placeholder="Bairro" value={clientNeighborhood} onChange={e => setClientNeighborhood(e.target.value)} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-4 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">Município</label><input type="text" placeholder="Cidade" value={clientCity} onChange={e => setClientCity(e.target.value)} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-2 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">UF</label><select value={clientState} onChange={e => setClientState(e.target.value)} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="" className="text-black bg-white">UF</option>{UF_LIST.map(uf => <option key={uf} value={uf} className="text-black bg-white">{uf}</option>)}</select></div>
                                    <div className="md:col-span-3 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">Telefone / Zap</label><input type="text" placeholder="(00) 00000-0000" value={clientPhone} onChange={e => setClientPhone(maskPhone(e.target.value))} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-3 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">Nascimento</label><input type="text" placeholder="dd/mm/aaaa" value={clientDob} onChange={e => setClientDob(maskDateStrict(e.target.value))} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-12 space-y-1"><label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider ml-3 mb-1 block">E-mail</label><input type="email" placeholder="cliente@email.com" value={clientEmail} onChange={e => setClientEmail(e.target.value)} className="w-full p-5 rounded-[1.5rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                </div>
                            </div>

                            <div id="item-form-section" className="md:col-span-12 border border-amber-500/20 bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-md rounded-[2.5rem] p-10 shadow-lg shadow-amber-500/10 transition-all duration-300 hover:shadow-amber-500/20 hover:border-amber-500/30">
                                <h3 className="text-xl font-bold text-slate-200 mb-8 flex items-center gap-4 font-display"><div className="p-3 bg-gradient-to-br from-amber-500/20 to-yellow-500/10 rounded-2xl shadow-lg shadow-amber-500/20 text-amber-400 border border-amber-500/30"><Icons.Package className="w-6 h-6" /></div> Itens da Venda</h3>
                                <div className="grid grid-cols-1 md:grid-cols-12 gap-5 mb-8">
                                    <div className="md:col-span-1"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Qtd</label><input type="number" min="1" value={newItemQty} onChange={e => setNewItemQty(parseInt(e.target.value))} className="w-full p-4 rounded-[1.2rem] text-sm text-center font-bold outline-none bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-2"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Tipo</label><select value={newItemType} onChange={e => setNewItemType(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm outline-none bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="" className="bg-white text-black">Selecione</option>{PRODUCT_TYPES.map(t => <option key={t} value={t} className="bg-white text-black">{t}</option>)}</select></div>
                                    <div className="md:col-span-5"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Descrição</label><input type="text" placeholder="Produto" value={newItemDesc} onChange={e => setNewItemDesc(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-2"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">RAM/Store</label><select value={newItemRam} onChange={e => setNewItemRam(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm outline-none bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="" className="bg-white text-black">Selecione</option>{RAM_STORAGE_OPTIONS.map(o => <option key={o} value={o} className="bg-white text-black">{o}</option>)}</select></div>
                                    <div className="md:col-span-2"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Cor</label><input type="text" placeholder="Cor" value={newItemColor} onChange={e => setNewItemColor(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-3"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">IMEI <span className="text-amber-500 normal-case">(validado)</span></label><input type="text" inputMode="numeric" placeholder="IMEI (15 dígitos)" value={newItemImei} onChange={e => setNewItemImei(maskIMEI(e.target.value))} className="w-full p-4 rounded-[1.2rem] text-sm font-mono outline-none font-medium shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className="md:col-span-2"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Financiado</label><select value={newItemFinanced} onChange={e => setNewItemFinanced(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm outline-none bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="Não" className="bg-white text-black">Não</option><option value="Sim" className="bg-white text-black">Sim</option></select></div>
                                    {category === 'Troca' && (<div className="md:col-span-2"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Movimento</label><select value={exchangeAction} onChange={e => setExchangeAction(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm font-bold text-slate-200 outline-none bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="out" className="bg-white text-black">Cliente está Levando</option><option value="in" className="bg-white text-black">Devolução do Cliente</option></select></div>)}
                                    <div className="md:col-span-3"><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Preço Unit</label><input type="text" placeholder="0,00" inputMode="numeric" value={newItemPrice} onChange={handleItemPriceChange} className="w-full p-4 rounded-[1.2rem] text-sm text-right font-bold outline-none shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className={category === 'Troca' ? "md:col-span-1" : "md:col-span-2"}><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">% Desc</label><input type="text" placeholder="%" value={newItemDiscountPercent} onChange={handlePercentChange} className="w-full p-4 rounded-[1.2rem] text-sm text-center outline-none shadow-inner placeholder-slate-600 bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className={category === 'Troca' ? "md:col-span-1" : "md:col-span-2"}><label className="text-[10px] font-bold text-slate-500 uppercase ml-2 mb-1 block">Desc R$</label><input type="text" placeholder="0,00" value={newItemDiscount} onChange={handleDiscountValChange} className="w-full p-4 rounded-[1.2rem] text-sm text-right text-red-500 outline-none focus:ring-4 focus:ring-red-500/30 focus:border-red-500/50 transition-all shadow-inner focus:bg-white/10 placeholder-red-500/50 bg-white/5" /></div>
                                    <div className="md:col-span-12 flex gap-3">
                                        {editingItemId && (
                                            <button type="button" onClick={() => { setEditingItemId(null); setNewItemQty(1); setNewItemType(''); setNewItemDesc(''); setNewItemRam(''); setNewItemColor(''); setNewItemImei(''); setNewItemFinanced('Não'); setNewItemPrice(''); setNewItemDiscount(''); setNewItemDiscountPercent(''); }} className="flex-none px-6 py-5 bg-white/5 border border-white/20 text-slate-400 rounded-[1.5rem] font-bold text-sm hover:bg-white/10 active:scale-[0.98] transition-all uppercase tracking-wide">Cancelar</button>
                                        )}
                                        <button type="button" onClick={handleAddItem} className={`flex-1 rounded-[1.5rem] py-5 text-sm active:scale-[0.98] transition-all uppercase tracking-wide relative overflow-hidden ${editingItemId ? 'bg-gradient-to-r from-emerald-500 via-green-400 to-emerald-500 text-white shadow-lg shadow-emerald-500/40 hover:shadow-emerald-500/60' : 'btn-gold'}`}>
                                            {editingItemId && <span className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full hover:animate-shimmer"></span>}
                                            {editingItemId ? '✏️ Salvar Alterações' : 'Adicionar Item • Lista'}
                                        </button>
                                    </div>
                                </div>
                                {items.length > 0 && (<div className="overflow-hidden border border-white/10 rounded-[2rem] bg-white/5 shadow-sm backdrop-blur-sm"><table className="w-full text-left text-sm"><thead className="bg-white/5 border-b border-white/10 text-xs text-slate-500 uppercase font-bold tracking-wider"><tr><th className="p-5 text-center">Qtd</th><th className="p-5 text-left">Produto Detalhado</th><th className="p-5 text-right">Preço</th><th className="p-5 text-right">Desconto</th><th className="p-5 text-right">Total</th><th className="p-5 w-20"></th></tr></thead><tbody className="divide-y divide-white/10">{items.map(i => (<tr key={i.id} className={`hover:bg-white/5 transition-colors ${i.unitPrice < 0 ? 'bg-red-500/10' : ''} ${editingItemId === i.id ? 'ring-2 ring-inset ring-odoo-500/40 bg-odoo-500/5' : ''}`}><td className="p-5 font-bold text-center text-slate-300">{i.quantity}</td><td className="p-5"><div className="font-bold text-slate-200">{i.type} - {i.description}</div><div className="text-xs text-slate-500 mt-1 flex gap-2 font-medium">{i.ram_storage && <span className="bg-white/5 px-2 py-0.5 rounded-md border border-white/10">{i.ram_storage}</span>}{i.color && <span className="bg-white/5 px-2 py-0.5 rounded-md border border-white/10">{i.color}</span>}<span className="bg-white/5 px-2 py-0.5 rounded-md border border-white/10">Finan: {i.financed}</span></div></td><td className="p-5 text-right font-mono text-slate-300">{formatCurrency(i.unitPrice)}</td><td className="p-5 text-right font-mono text-red-400">-{formatCurrency(i.discount)}</td><td className="p-5 text-right font-mono font-bold text-slate-200">{formatCurrency((i.unitPrice * i.quantity) - i.discount)}</td><td className="p-5"><div className="flex items-center justify-center gap-1"><button type="button" onClick={() => handleEditItem(i)} className="p-2 hover:bg-odoo-500/10 text-slate-500 hover:text-odoo-400 rounded-xl transition-colors active-scale" title="Editar item"><Icons.Edit className="w-4 h-4" /></button></div></td></tr>))}</tbody></table></div>)}
                            </div>

                            <div className="md:col-span-12 border border-amber-500/20 bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-md rounded-[2.5rem] p-10 shadow-lg shadow-amber-500/10 transition-all duration-300 hover:shadow-amber-500/20 hover:border-amber-500/30">
                                <h3 className="text-xl font-bold text-slate-200 mb-8 flex items-center gap-4 font-display"><div className="p-3 bg-gradient-to-br from-amber-500/20 to-yellow-500/10 rounded-2xl shadow-lg shadow-amber-500/20 text-amber-400 border border-amber-500/30"><Icons.DollarSign className="w-6 h-6" /></div> Pagamento</h3>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center mb-10"><div className="bg-white/5 p-5 border border-white/10 rounded-[2rem] shadow-sm"><p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2">Subtotal</p><p className="text-2xl font-bold text-slate-200">{formatCurrency(totalAmount)}</p></div><div className="bg-white/5 p-5 border border-white/10 rounded-[2rem] shadow-sm"><p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2">Descontos</p><p className="text-2xl font-bold text-red-400">-{formatCurrency(totalDiscount)}</p></div><div className="bg-odoo-500/10 p-5 border border-odoo-500/20 rounded-[2rem] shadow-inner"><p className="text-xs font-bold text-odoo-500 uppercase tracking-widest mb-2">A Pagar</p><p className="text-4xl font-black text-odoo-400 tracking-tight">{formatCurrency(finalTotal)}</p></div></div>
                                <div className="grid grid-cols-1 md:grid-cols-12 gap-5 items-end mb-8">
                                    <div className="md:col-span-3"><label className="text-xs font-bold text-slate-500 uppercase ml-2 mb-1 block">Forma</label><select value={currentPaymentMethod} onChange={e => setCurrentPaymentMethod(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm tracking-tight outline-none font-medium shadow-inner bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="" className="bg-white text-black">Selecione...</option>{PAYMENT_METHODS.map(m => <option key={m} value={m} className="bg-white text-black">{m}</option>)}{(category === 'Devolução' || category === 'Troca') && (<><option value="Devolução Dinheiro" className="bg-white text-black">Devolução Dinheiro</option><option value="Devolução Pix" className="bg-white text-black">Devolução Pix</option><option value="Devolução Estorno Cartão" className="bg-white text-black">Devolução Estorno Cartão</option><option value="Cancelado na Financeira" className="bg-white text-black">Cancelado na Financeira</option></>)}</select></div>
                                    {currentPaymentMethod === 'Credito Parcelado' && (<div className="md:col-span-2"><label className="text-xs font-bold text-slate-500 uppercase ml-2 mb-1 block">Parc.</label><select value={currentInstallments} onChange={e => setCurrentInstallments(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm outline-none font-medium shadow-inner bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="" className="bg-white text-black">Qtd</option>{[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map(i => <option key={i} value={`${i}x`} className="bg-white text-black">{i}x</option>)}</select></div>)}
                                    <div className={currentPaymentMethod === 'Credito Parcelado' ? "md:col-span-2" : "md:col-span-3"}><label className="text-xs font-bold text-slate-500 uppercase ml-2 mb-1 block">Tipo</label><select value={currentPaymentType} onChange={e => setCurrentPaymentType(e.target.value)} className="w-full p-4 rounded-[1.2rem] text-sm tracking-tight outline-none font-medium shadow-inner bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all"><option value="" className="bg-white text-black">Selecione...</option>{PAYMENT_TYPES.map(t => <option key={t} value={t} className="bg-white text-black">{t}</option>)}</select></div>
                                    <div className="md:col-span-3"><label className="text-xs font-bold text-slate-500 uppercase ml-2 mb-1 block">Valor</label><input type="text" value={currentPaymentAmount} onChange={handleCurrentPaymentAmountChange} className="w-full p-4 rounded-[1.2rem] text-sm text-right font-bold outline-none shadow-inner bg-white/5 focus:bg-white/10 focus:shadow-lg focus:shadow-amber-500/20 focus:border focus:border-amber-500/30 transition-all" /></div>
                                    <div className={currentPaymentMethod === 'Credito Parcelado' ? "md:col-span-2 flex gap-2" : "md:col-span-3 flex gap-2"}>
                                        {editingPaymentId && (
                                            <button type="button" onClick={() => { setEditingPaymentId(null); setCurrentPaymentMethod(''); setCurrentPaymentType(''); setCurrentPaymentAmount(''); setCurrentInstallments(''); }} className="flex-none px-4 py-4 bg-red-500/10 border border-red-500/30 text-red-400 rounded-[1.2rem] font-bold text-xs hover:bg-red-500/30 hover:text-red-300 hover:border-red-500/50 active-scale transition-all uppercase tracking-wide z-10 relative shadow-lg shadow-red-500/20">✕</button>
                                        )}
                                        <button type="button" onClick={handleAddPayment} className={`flex-1 font-bold rounded-[1.2rem] py-4 text-sm whitespace-nowrap transition-all uppercase tracking-wide relative overflow-hidden ${editingPaymentId ? 'bg-gradient-to-r from-emerald-500 via-green-400 to-emerald-500 text-white shadow-lg shadow-emerald-500/40 hover:shadow-emerald-500/60 active:scale-95 active:shadow-inner active:shadow-emerald-600/50' : 'bg-gradient-to-r from-[#A1B5C9] via-[#C0D1DE] to-[#A1B5C9] text-[#0f0f0f] shadow-lg shadow-slate-400/30 hover:shadow-slate-500/50 border border-slate-300/30 active:scale-95 active:shadow-inner active:shadow-slate-500/60'}`}>
                                            {!editingPaymentId && <span className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent -translate-x-full hover:animate-shimmer"></span>}
                                            {editingPaymentId ? '✏️ Salvar' : 'Add Pgto'}
                                        </button>
                                    </div>
                                </div>
                                <div className="bg-white/5 border border-white/10 rounded-[2rem] overflow-hidden shadow-sm backdrop-blur-sm">
                                    <table className="w-full text-left text-xs"><thead className="bg-white/5 border-b border-white/10 text-slate-500 font-bold uppercase tracking-wider"><tr><th className="p-5">Forma</th><th className="p-5 text-right">Valor</th><th className="p-5 w-20"></th></tr></thead><tbody>{paymentList.map(p => { const styles = getPaymentStyles(p.type); return (<tr key={p.id} className={`border-b border-white/10 last:border-0 ${editingPaymentId === p.id ? 'ring-2 ring-inset ring-odoo-500/40 bg-odoo-500/5' : ''}`}><td className="p-5"><span className="font-bold text-slate-300 text-sm">{p.method}</span> {p.installments && <span className="ml-1 text-slate-500">({p.installments})</span>}<span className="ml-2 px-2 py-0.5 rounded-md bg-white/10 border border-white/10 text-slate-400 font-bold text-[10px] uppercase tracking-wide">{p.type}</span></td><td className={`p-5 text-right font-mono font-bold text-sm ${styles.amount}`}>{formatCurrency(p.amount)}</td><td className="p-5"><div className="flex items-center justify-center gap-1"><button type="button" onClick={() => handleEditPayment(p)} className="text-slate-500 hover:text-odoo-400 transition-colors p-1.5 hover:bg-odoo-500/10 rounded-lg" title="Editar"><Icons.Edit className="w-4 h-4" /></button><button type="button" onClick={() => handleRemovePayment(p.id)} className="text-slate-500 hover:text-red-500 transition-colors p-1.5 hover:bg-white/10 rounded-lg" title="Remover"><Icons.Trash2 className="w-4 h-4" /></button></div></td></tr>); })}</tbody></table>
                                    <div className="p-6 bg-[#fdfaf4] space-y-3 border-t border-[#0f0f0f]/10">
                                        <div className="flex justify-between items-center"><span className="font-bold text-xs uppercase text-slate-500 tracking-wider">Restante a pagar</span> <span className="text-red-400 font-mono font-bold text-lg">{formatCurrency(remainingToPay)}</span></div>
                                        <div className="flex justify-between items-center"><span className="font-bold text-xs uppercase text-slate-500 tracking-wider">Total Recebido</span> <span className="text-green-400 font-mono font-black text-xl">{formatCurrency(totalPaid)}</span></div>
                                        {changeAmount > 0.02 && (
                                            <div className="flex justify-between items-center pt-2 border-t border-[#0f0f0f]/10"><span className="font-bold text-xs uppercase text-slate-500 tracking-wider">Troco</span> <span className="text-orange-500 font-mono font-bold text-lg">{formatCurrency(changeAmount)}</span></div>
                                        )}
                                        <div className="pt-3 border-t border-[#0f0f0f]/10 mt-2">
                                            <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1 block">Observação no Pagamento</label>
                                            <input type="text" value={paymentObservation} onChange={e => setPaymentObservation(e.target.value)} placeholder="Ex: Transferência agendada..." className="w-full p-2.5 rounded-xl outline-none text-xs font-medium shadow-inner border border-[#0f0f0f]/10 bg-white/50 text-[#0f0f0f] placeholder:text-slate-400" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="border border-amber-500/20 bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-md rounded-[1.5rem] p-5 shadow-lg shadow-amber-500/10 flex items-center gap-4 transition-all duration-300 hover:shadow-amber-500/20 hover:border-amber-500/30">
                            <div className="p-2.5 bg-gradient-to-br from-amber-500/20 to-yellow-500/10 rounded-xl shadow-lg text-amber-400 border border-amber-500/30 shrink-0"><Icons.UserPlus className="w-5 h-5" /></div>
                            <h3 className="text-base font-bold text-slate-200 font-display whitespace-nowrap">Conheceu a loja?</h3>
                            <div className="flex-1 ml-2">
                                <input type="text" list="source-options" placeholder="Digite ou selecione..." value={clientSource} onChange={e => setClientSource(e.target.value)} className="w-full p-3.5 rounded-[1.5rem] outline-none text-sm font-medium shadow-inner placeholder:text-slate-400 text-[#0f0f0f] focus:shadow-lg focus:shadow-amber-500/20 focus:border-amber-500/30 border border-transparent focus:border-amber-500/30 transition-all" />
                                <datalist id="source-options">
                                    <option value="Instagram" />
                                    <option value="Facebook" />
                                    <option value="Pri Almeida" />
                                </datalist>
                            </div>
                        </div>

                        <div className="flex gap-5 pt-6 border-t border-white/10">{editingId && (<button type="button" onClick={resetForm} className="w-1/3 py-5 rounded-[2rem] font-bold text-slate-400 bg-white/5 border border-white/10 hover:bg-white/10 hover:text-white transition-all active-scale text-base uppercase tracking-wide shadow-sm">Cancelar</button>)}<button type="submit" className={`flex-1 py-5 rounded-[2rem] font-black shadow-vision transition-all active-scale text-lg uppercase tracking-wide btn-gold`}>{editingId ? "Atualizar Registro" : "Finalizar Lançamento"}</button></div>
                    </form>
                </div>
            </div>
        </>
    );
};

export default SalesForm;